### PR TITLE
Fix waiting for frontendlib app port

### PR DESCRIPTION
**Pull request by simomat**
Fix for #223
Tested locally with my app.

### CODE REVIEW

**Review by shalithasuranga — APPROVED** [review]
Thanks so much your contribution :tada:

**Comment by KTibow** [comment]
This seems to have made it impossible for me to use the dev server. Even though port 5173 is being used, it just says "application will be launched when .. is ready" and eventually gives up.

**Comment by simomat** [comment]
I can't see how this patch could be the reason, because it only removes the hard coded port. Seems more like 18a2fed doesn't work for you somehow. (You could check by using v10.0.0 which includes 18a2fed but not this patch.)

**Comment by KTibow** [comment]
@simomat ah nvm then, missed that. Regardless I sent in https://github.com/neutralinojs/neutralinojs-cli/pull/235 to fix this.

**Pull request merged**
