### PR TITLE
Add --export-auth-info only if set true in config.json

### PR DESCRIPTION
**Pull request by pathange-s**
Fixes neutralinojs/neutralinojs#892
- To export auth info, set `"exportAuthInfo": true"` in neutralino.config.json
- By default, export auth info will be set true. I will drop PRs for the same

### CODE REVIEW

**Comment by pathange-s** [comment]
The error linked occurred because the flag to export auth info `--export-auth-info` was being passed every time irrespective of if it is set to true or false. Check [here](https://github.com/neutralinojs/neutralinojs-cli/blob/a03221582ca47d5f43c4ac8fb0198d8e3d85af7e/src/modules/runner.js#L35). This PR fixes it by only exporting if the `exportAuthInfo` attribute is set to true.

**Comment by shalithasuranga** [comment]
Hey.. thanks for sending this pull request. The issue is that `--export-auth-info` is needed for CLI to connect with the framework. Also, `--neu-dev-extension` is needed along with export info. Otherwise, the CLI can't establish a WebSocket connection due to missing credentials. As a result, the CLI keeps re-trying connection forever ;) 

Maybe we can explain the scenario in the original issue? `neu run` is a command for developers -- not users. So, this behavior makes sense guess. WDYT?

**Comment by pathange-s** [comment]
I am not very sure about the internal architecture of the application, the way it connects and makes connections.
By what you said, it makes sense. Also, this means that we need to update the documentation. Currently the documentation states that we can set `exportAuthInfo` true or false. (Or does that mean that these will be set once the application gets ready to shipping stage) . Check [here](https://neutralino.js.org/docs/cli/internal-cli-arguments/#--export-auth-infotruefalse)

**Comment by shalithasuranga** [comment]
Hey.. I have to close this PR since we need to have this option always on to get the CLI working properly with the application. Perhaps, we can update the documentation instead. Let's see whether someone has a question related with this again. Thanks for sending this PR :tada:

**Pull request closed without merging**
