### PR TITLE
:sparkles: Set icons and metadata to Windows executables

### PR DESCRIPTION
**Pull request by CosmoMyzrailGorynych**
Closes the following issues:

* https://github.com/neutralinojs/neutralinojs/issues/1057
* https://github.com/neutralinojs/neutralinojs-cli/issues/84 (was previously closed as "not planned")

This PR allows the `neu build` command to patch Windows executables with user-provided metadata and icon. This all is fully cross-platform. Icons are accepted in PNG format for ease of use and use in possible further improvements on making MacOS or Linux packages.

This introduces the following optional keys to `neutralino.config.json`: (the keys are top-level)

* `author`: gets written into executable's metadata.
* `description`: gets written into executable's metadata.
* `copyright`: gets written into executable's metadata. Defaults to current date + generic "all rights reserved".
* `applicationName`: gets written into executable's metadata. Defaults to `cli.binaryName`.
* `applicationIcon`: a relative path to an icon in `.png` format. Defaults to `modes.window.icon`. If it is not set, uses Neutralinojs logo.

Two npm packages were introduced as direct dependencies: 

* [resedit](https://www.npmjs.com/package/resedit)
* [png2icons](https://www.npmjs.com/package/png2icons), this package can also be used in the future to bake icons for MacOS.

No native or platform-specific dependencies. Yay!

Possible backwards incompatibility:

* If a user doesn't fill any of the new fields AND has an icon in `modes.window.icon` that is not in PNG format, the `neu build` command will fail as the windows patcher expects an icon in a PNG format. Perhaps I shouldn't look for an icon in `modes.window.icon` at all?

I'm open to improvements of this PR and will also make a PR for docs if/when this gets approved.

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
Example output:
изображение

Not setting any of the new fields still produces a .exe with a nice icon:
изображение

**Review by shalithasuranga — CHANGES_REQUESTED** [review]
Hello @CosmoMyzrailGorynych  Thanks so much for your pull request. Please note that, at this moment of the project, we need to support older Node versions. Could you please adhere to [this notice](https://github.com/neutralinojs/neutralinojs-cli?tab=readme-ov-file#%EF%B8%8F-notice-for-contributors) and use `||` and ternary if instead of `?.` and `??`. Thanks :tada:

Edit: Also, please make sure to resolve conflicts, Thanks

**Comment by CosmoMyzrailGorynych** [comment]
Sure

**Comment by CosmoMyzrailGorynych** [comment]
I assume you're targeting node.js v8+. Is it correct?

**Comment by CosmoMyzrailGorynych** [comment]
🤔 Readme tells you need Node.js v14+ but `??` and `?.` was introduced exactly in v14.0.0. What version is the minimum one???

**Comment by shalithasuranga** [comment]
Hello, thanks for posting your findings. According to [this issue](https://github.com/neutralinojs/neutralino.js/issues/71), seems like the minimum version should be 12 (We need to update the readme file it sounds :) ). Thanks :tada:

**Comment by CosmoMyzrailGorynych** [comment]
@shalithasuranga done.

**Comment by shalithasuranga** [comment]
@CosmoMyzrailGorynych thanks so much. Soory the trouble, could you please sync with the latest code. Thanks so much :tada:

**Comment by CosmoMyzrailGorynych** [comment]
@shalithasuranga done.

**Comment by CosmoMyzrailGorynych** [comment]
Btw, in case a question rises where executables should ever be patched when Neutralino is inside a host project, one often overlooked "feature" of Windows is antiviruses that love to block everything. Metadata and an icon will show in antiviruses' dialogs indicating that it is the app a user wants to run, not some "random, unknown" Neutralino 😄

**Review by shalithasuranga — APPROVED** [review]
Thanks so much for your work @CosmoMyzrailGorynych. I'll release a new version with the newly added features soon! We can update the documentation (by adding `config.author`, etc, and other details) after releasing the next version :tada:

**Comment by shalithasuranga** [comment]
> Btw, in case a question rises where executables should ever be patched when Neutralino is inside a host project, one often overlooked "feature" of Windows is antiviruses and firewalls that love to block everything. Metadata and an icon will show in antiviruses' and firewalls' dialogs indicating that it is the app a user wants to run, not some "random, unknown" Neutralino 😄
> 
> By the very same reason I'm patching Bun binaries when it is run by Neutralino.

Yeah, this feature is great for every Windows's Neutralinojs app user and app developer. Thanks :tada:

**Comment by CosmoMyzrailGorynych** [comment]
Thank you for merging it. I will prepare a follow-up PR for docs soon.
You should probably close this issue: https://github.com/neutralinojs/neutralinojs/issues/1057

**Comment by shalithasuranga** [comment]
Sure @CosmoMyzrailGorynych thanks :tada: The issue is closed now :tada:

**Pull request merged**
