### PR TITLE
[WIP]: webpack bundler added

### LINKED ISSUE #78: Bundle size is huge! Even larger than Electron?!
Just tried using neutralinojs, tauri and electron to package a Vue-based website and did a quick comparison. Surprisingly, neutralinojs produces the largest binary! res.neu is incredibly 75 MB and it has to be bundled with executable file to work properly. I am using the latest neu.

### PR DESCRIPTION
**Pull request by viralgupta**
Right now we are building binaries from raw javascript files given, this pr helps to reduce app size a bit by bundling js files.

i have tested with few apps and is working fine, @shalithasuranga could you also review this on your machine.

may-resolve #78

### CODE REVIEW

**Review by shalithasuranga — COMMENTED** [review]
Hello @viralgupta, thanks for sending this PR. Could you please compare the benefits of using https://www.npmjs.com/package/node-minify. Seems like it supports wildcard path matches, so we don't need to parse `index.html` manually. Thanks :tada:

**Review by CosmoMyzrailGorynych — COMMENTED** [review]
I'm against this and any PRs that arbitrarily mangle user's input. If I was a maintainer, I would veto it. If I was a user with that PR merged, I would simply not use Neutralino.js. Everyone uses their preferable build tools already and having the slowest and oldest possible packer mangle scripts is pointless, dangerous, and inflexible.

* Bundling JS files just to minify them in one file is one of the least concerns when developing a **desktop** app.
* ESM vs IIFE-type scripts are not handled here;
* No way to configure path rewriting and external modules;
* It's slow, there're dozens of popular options in the wild like vite, rollup, esbuild, etc.;
  * And the end user knows what to use better anyways.
* And, really, Webpack? in 2024?!

**Comment by viralgupta** [comment]
Hi @CosmoMyzrailGorynych,
Thank you for your feedback. I agree with all the points you've mentioned, and I had similar thoughts after creating this PR. That's why I drafted the PR, and I'm now closing it (I should have closed it earlier).

Please note: This was my first time contributing to open source, and I wanted to close issues quickly and genuinely wanted to help the community. However, I had little to no knowledge of the available bundling technologies when I created this PR. I apologize for any inconvenience caused.

**Comment by CosmoMyzrailGorynych** [comment]
That's ok, I'm glad you're growing as a developer.

**Pull request closed without merging**
