### PR TITLE
Feat: support project runner

### PR DESCRIPTION
**Pull request by viralgupta**
Supported to init, run, build Neutralino Apps with project runner

- supports neu config parameters like so under cli
```json
    "projectRunner": {
      "projectPath": "/",
      "buildPath": "./node-src/dist/",
      "initCommand": "npm run runner:install",  
      "devCommand": "npm run runner:start",     
      "buildCommand": "npm run runner:build"
    }
```
- `initCommand`, `devCommand`, `buildCommand` are run inside root of the Neu App
- could not understand the need of `type` attribute so did not include it

Todo: (in this [repo](https://github.com/neutralinojs-community/node-neutralino))

- add logic for running frontend library
- run binaries with new name when in build mode

### CODE REVIEW

**Review by shalithasuranga — APPROVED** [review]
Thanks so much for your contribution @viralgupta :tada:

**Review by CosmoMyzrailGorynych — COMMENTED** [review]
I don't think this approach is good in the long term. Neutralino.js is a simple framework that has its precise purpose and I would rather leave it be that way. Any framework built on top of Neutralino.js should use its builds programmatically and sort its files on its own, and provide its own CLIs to run apps. There are also options like using npm scripts instead of expanding neutralino.js API.

About the code itself,
The `bin` folder is hard-coded (bad, needs configs as future frameworks may already use the `bin` folder) and the code for moving the neutralino files could instead be merged with the loop above to simplify the code and remove excess file operations.
Also, please add code comments. The `'Copying Project Runner build...'` part has just one line that does exactly that in the whole if branch.

**Comment by shalithasuranga** [comment]
Thanks so much for your feedback @CosmoMyzrailGorynych. Please note that this PR simply lets a GSoC contributor run his community project idea (named [NodeNeutralino](https://github.com/neutralinojs-community/node-neutralino)). This is directly merged but improved with https://github.com/neutralinojs/neutralinojs-cli/commit/498735360b130dd3da09f831fd6989f5e3df493b as the GSoC contributor's main focus is NodeNeutralino - not working with the CLI. 

This hostProject (previously projectRunner) delivers a concept where someone can use Neutralinojs with custom backends (not extensions). The idea is explained in [official docs](https://neutralino.js.org/docs/how-to/extensions-overview#using-neutralinojs-from-your-source-files). We would like to see PyNeutralino, GoNeutralino, etc. they are just bindings for Neutralino ;)

Thanks :tada:

**Comment by CosmoMyzrailGorynych** [comment]
I understood the concept of this PR, that is is about NeutralinoNode, yet my points still stand. Tailoring a more general-use framework towards one use case is not a good idea imo.

**Pull request merged**
