### PR TITLE
Used console.log instead of figlet

### LINKED ISSUE #262: Remove `figlet` by printing an ASCII art directly with console.log

### PR DESCRIPTION
**Pull request by viralgupta**
closes #262 
- Removed figlet from dependencies
- use \b (backspace characters) to keep the formating of the document while not increasing the width of the ascii banner

### CODE REVIEW

**Comment by Sadaf-A** [comment]
Hey, do you think it is good make sure that the text remains the same? this will add one extra space on the top and will not have a left margin as the figlet text did

**Comment by viralgupta** [comment]
Hi sadaf, thankyou for pointing out. it did had an extra new line above and below the ascii art which I have removed, but margin of one space on the left is same as figlet.
We can also increase or decrease the left margin by removing or adding the **\b** character from each line

**Comment by Sadaf-A** [comment]
Hey @viralgupta , 
It seems like the text is not coming out as expected I think there is an extra space on the first line

**Comment by shalithasuranga** [comment]
Thanks so much @viralgupta for working on this task. I had to merge #264 instead of this since it doesn't contain visible escape characters..

**Pull request closed without merging**
