### PR TITLE
Now plugins wont disappear if user upgrades CLI

### LINKED ISSUE #83: Check and improve plugin system
Now the plugins will disappear if the user upgrades the CLI. Try to check and improve this behavior

### PR DESCRIPTION
**Pull request by pathange-s**
Fixes #83 

- User can now upgrade CLI tool without loosing previously installed plugins.

### CODE REVIEW

**Comment by pathange-s** [comment]
Will add tests to this PR itself once #125 is merged.

**Comment by shalithasuranga** [comment]
Hey.. @pathange-s, now #125 was merged :tada:

**Comment by pathange-s** [comment]
Will drop a PR with tests for the same ;)

**Comment by pathange-s** [comment]
Created a separate module to test internal functionality of `plugins` I did append the same code to `test_commands.sh` but that script seems specific to just run and test commands but not errors / enhancements.

**Review by shalithasuranga — APPROVED** [review]
Hey.. now this looks great. I did a few updates here and there to tweak this a bit. The solution for automatic plugin installation is a great idea :tada:

**Review by shalithasuranga — APPROVED** [review]

**Comment by pathange-s** [comment]
@shalithasuranga Great Work, Looked into how you refactored code. Seems good improvements.

**Pull request merged**
