### PR TITLE
Feat: ignore files support added

### LINKED ISSUE #218: resourcePath bundler: ignore certain file extensions
Right now,  `neu build` bundles all files from the `resourcePath`(provided in `neutralino.config.json`) into one `resources.neu` file.
Thereby, files can be included that have **no use** there (like TypeScript files).
It would be very handy if there was an option in the `neutralino.config.json` to ignore certain file extensions. 

here an example:

```json
{
 "cli": {
  "binaryName": "neutralino",
  "resourcesPath": "/resources/",
  "resourcesIgnore": [".ts", "*.scss", "sandbox.js"],
  "extensionsPath": "/extensions/",
  "extensionsIgnore": ["*.ts", ".gitignore", "randomFileInExtensionFolderThatWeDon'tWantBundled.extension"],
  "clientLibrary": "/resources/js/neutralino.js",
  "binaryVersion": "4.6.0",
  "clientVersion": "3.5.0"
 }
}
```
Of course it can be implemented differently, e.g. in a `.neuignore` file, but I think it is more convenient to have everything in one configuration file, like in the example above.

**.neuignore**
```
/myCoolResources/*.ts
/extensions/*.mjs
```

Thanks and have great day! :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by viralgupta**
closes #218 

docs for this pr [#309](https://github.com/neutralinojs/neutralinojs.github.io/pull/309)

### CODE REVIEW

**Comment by viralgupta** [comment]
Hi @shalithasuranga, thank you for highlighting best practices. I've removed `glob` as a dependency and replaced it with anymatch, which is the same library utilized by chokidar in `autoReloadExclude`. By including `anymatch` in package.json, we avoid increasing the size of `node_modules` and instead rely on an existing subdependency.

However, the format for excluding files in `cli.autoReloadExclude` (`".*\\.scss$|.*\\.less$"`) differs from the format we use for `cli.resourceIgnore` files (`["*.ts", "*.tsx"]`). In `cli.resourceIgnore`, we use an array of patterns rather than a single string with patterns separated by `|`. Should we maintain a consistent format for ignoring files throughout the configuration file?

**Comment by shalithasuranga** [comment]
Thanks so much for your update. Could you please implement this the same as the `autoReloadExclude` option without linking another dependency? Thank you :tada: I think all developers who use Neutralinojs know about Regex, so we don't need to worry about using an array :tada:

**Comment by viralgupta** [comment]
Hi @shalithasuranga, I have implemented regex pattern matching and dropped glob pattern matching.
I just wanted to confirm: should we drop glob pattern matching even though this was what was requested in the original issue?
> "resourcesExclude": [".*\.js$"]

If we are okay with regex matching, then I think we can merge this PR.

**Comment by shalithasuranga** [comment]
This is now merged, Thanks :) Please note that I've done some changes in: https://github.com/neutralinojs/neutralinojs-cli/commit/2a6d21c6466a31c20eb41fde67684f2bca63305b

**Pull request merged**
