### PR TITLE
added logo to README.md

### LINKED ISSUE #163: Create new logo for neu cli
Ideas can be drawn from something similar to this
https://github.com/spf13/cobra
https://github.com/jarun/googler
https://github.com/browsh-org/browsh

### PR DESCRIPTION
**Pull request by BhuvanAde**
added logo to README.md Fixes #163

### CODE REVIEW

**Comment by BhuvanAde** [comment]
Please let me know if there are any other changes that need to be made.

**Comment by shalithasuranga** [comment]
Hey @BhuvanAde, thanks for sending this merge request. Could you please create a directory named `./media` and add the Logo you've created there, then link it? We can merge this after these changes :)

**Comment by BhuvanAde** [comment]
@shalithasuranga I've made the suggested changes; please let me know if you have any other suggestions.

**Review by shalithasuranga — APPROVED** [review]
Thanks so much for the contribution :tada:

**Pull request merged**
