### PR TITLE
Update hot reload patch wording

### PR DESCRIPTION
**Pull request by KTibow**

### CODE REVIEW

**Review by shalithasuranga — COMMENTED** [review]
Hi @KTibow, Thanks for sending this pull request. We have to close this since it exessively adds "Neutralinojs". We already display "neu: " prefix with every log that Neutralinojs CLI prints. Please check [log function sources](https://github.com/neutralinojs/neutralinojs-cli/blob/0e4ce1beb650db958742143d896921d88a875928/src/utils.js#L33).

Thanks, we hope you will contribute Neutralinojs with another pull request again :)

**Comment by KTibow** [comment]
@shalithasuranga my reasoning:
- "hot reload patch" doesn't make sense. it patches in the NEU lib, not hot reloading. the part where it loads the hot reloading instead of the static build is separate.
- the thing it does is patch in the NEU lib and/or the NEU globals. that's why it makes sense to say Neutralinojs. it isn't referring to the same thing as the CLI is.

is there a better term instead that you would use?

**Comment by shalithasuranga** [comment]
Thanks for the explanation. Mm. yeah, we can improve this term seems. I think we named it as "hot reload patch" because it enables HMR support for a "Neutralinojs app". I mentioned as above since we use "Neutralinojs" also with "neu:" prefix which looks a bit redundant. 

Maybe we can use one of the following terms I guess considering your suggestion:
- "Neutralinojs global variables patch"
- "Global variables patch"
- "Neutralinojs server patch"

Or, do you have another suggesion that gives the meaning of above terms? Please update the PR with a better term without code formatting changes. We can re-open this and merge I think :tada:

Thanls :tada:

**Comment by KTibow** [comment]
I'll make a new PR because it's easier that way (would rather not reset this branch + its impossible for me to reopen this PR)

**Pull request closed without merging**
